### ISSUE TITLE
when i run : rake xdr:generate , the result rake aborted

### ISSUE THREAD

**Issue by ArthurZangCN** [stellar/go#1442]
horizon version : 0.18.1
os : ubuntu 16.04 x64
golang version : 1.12
rake version : 12.3.1
bundler version : 1.11.2

when i run "rake xdr:generate" to rebuild xdr file , the result rake aborted! the 0.17 and before has no problem。detailed list ：
** Invoke xdr:generate (first_time)
** Execute xdr:generate
rake aborted!
NoMethodError: undefined method `members' for nil:NilClass
/var/lib/gems/2.3.0/bundler/gems/xdrgen-c56e3ff84b32/lib/xdrgen/ast/definitions/union.rb:22:in `resolved_case'
/var/lib/gems/2.3.0/bundler/gems/xdrgen-c56e3ff84b32/lib/xdrgen/generators/go.rb:536:in `block (2 levels) in switch_for'
/var/lib/gems/2.3.0/bundler/gems/xdrgen-c56e3ff84b32/lib/xdrgen/generators/go.rb:533:in `each'
/var/lib/gems/2.3.0/bundler/gems/xdrgen-c56e3ff84b32/lib/xdrgen/generators/go.rb:533:in `block in switch_for'
/var/lib/gems/2.3.0/bundler/gems/xdrgen-c56e3ff84b32/lib/xdrgen/generators/go.rb:532:in `each'
/var/lib/gems/2.3.0/bundler/gems/xdrgen-c56e3ff84b32/lib/xdrgen/generators/go.rb:532:in `switch_for'
/var/lib/gems/2.3.0/bundler/gems/xdrgen-c56e3ff84b32/lib/xdrgen/generators/go.rb:289:in `render_union'
/var/lib/gems/2.3.0/bundler/gems/xdrgen-c56e3ff84b32/lib/xdrgen/generators/go.rb:173:in `render_definition'
/var/lib/gems/2.3.0/bundler/gems/xdrgen-c56e3ff84b32/lib/xdrgen/generators/go.rb:147:in `block in render_nested_definitions'
/var/lib/gems/2.3.0/bundler/gems/xdrgen-c56e3ff84b32/lib/xdrgen/generators/go.rb:147:in `each'
/var/lib/gems/2.3.0/bundler/gems/xdrgen-c56e3ff84b32/lib/xdrgen/generators/go.rb:147:in `render_nested_definitions'
/var/lib/gems/2.3.0/bundler/gems/xdrgen-c56e3ff84b32/lib/xdrgen/generators/go.rb:160:in `render_definition'
/var/lib/gems/2.3.0/bundler/gems/xdrgen-c56e3ff84b32/lib/xdrgen/generators/go.rb:141:in `block in render_definitions'
/var/lib/gems/2.3.0/bundler/gems/xdrgen-c56e3ff84b32/lib/xdrgen/generators/go.rb:141:in `each'
/var/lib/gems/2.3.0/bundler/gems/xdrgen-c56e3ff84b32/lib/xdrgen/generators/go.rb:141:in `render_definitions'
/var/lib/gems/2.3.0/bundler/gems/xdrgen-c56e3ff84b32/lib/xdrgen/generators/go.rb:142:in `block in render_definitions'
/var/lib/gems/2.3.0/bundler/gems/xdrgen-c56e3ff84b32/lib/xdrgen/generators/go.rb:142:in `each'
/var/lib/gems/2.3.0/bundler/gems/xdrgen-c56e3ff84b32/lib/xdrgen/generators/go.rb:142:in `render_definitions'
/var/lib/gems/2.3.0/bundler/gems/xdrgen-c56e3ff84b32/lib/xdrgen/generators/go.rb:12:in `generate'
/var/lib/gems/2.3.0/bundler/gems/xdrgen-c56e3ff84b32/lib/xdrgen/compilation.rb:26:in `compile'
/root/gocode/src/github.com/stellar/go/Rakefile:51:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/var/lib/gems/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => xdr:generate

**Comment by ArthurZangCN** [comment]
Gems included by the bundle:
  * activemodel (5.2.1)
  * activesupport (5.2.1)
  * addressable (2.5.2)
  * base32 (0.3.2)
  * bundler (1.11.2)
  * citrus (3.0.2)
  * coderay (1.1.2)
  * concurrent-ruby (1.0.5)
  * contracts (0.16.0)
  * digest-crc (0.4.1)
  * ethon (0.11.0)
  * excon (0.62.0)
  * faraday (0.9.2)
  * faraday-digestauth (0.3.0)
  * faraday_hal_middleware (0.1.0)
  * faraday_middleware (0.9.2)
  * ffi (1.9.25)
  * hyperclient (0.9.0)
  * i18n (1.1.0)
  * memoist (0.11.0)
  * method_source (0.9.0)
  * minitest (5.11.3)
  * multipart-post (2.0.0)
  * net-http-digest_auth (1.4.1)
  * netrc (0.11.0)
  * octokit (4.12.0)
  * pg (0.18.4)
  * polyglot (0.3.5)
  * pry (0.11.3)
  * public_suffix (3.0.3)
  * rake (12.3.1)
  * rbnacl (5.0.0)
  * rbnacl-libsodium (1.0.16)
  * sawyer (0.8.1)
  * sequel (5.5.0)
  * slop (3.6.0)
  * stellar-base (0.17.0)
  * stellar-sdk (0.5.0)
  * stellar_core_commander (0.0.13 154c81d)
  * thread_safe (0.3.6)
  * toml-rb (1.1.2)
  * treetop (1.5.3)
  * typhoeus (0.8.0)
  * tzinfo (1.2.5)
  * uri_template (0.7.0)
  * xdr (3.0.0)
  * xdrgen (0.0.1 c56e3ff)

**Comment by ArthurZangCN** [comment]
The problem has been solved. need run “bundle update”
