### ISSUE TITLE
Horizon 0.20.0 crashes on start

### ISSUE THREAD

**Issue by marcinx** [stellar/go#1643]
Trying to run horizon-0.20.0 (using https://github.com/stellar/go/releases/download/horizon-v0.20.0/horizon-v0.20.0-linux-amd64.tar.gz) results in below.

Steps:
* run migrations UP.
* run horizon the same way as Horizon 0.18.0 and earlier versions (except adding `Environment="ENABLE_EXPERIMENTAL_INGESTION=true"`) . 

-> Output as below. 

```
panic: (*logrus.Entry) (0xd92540,0xc0001e2050)

goroutine 1 [running]:
github.com/stellar/go/vendor/github.com/sirupsen/logrus.Entry.log(0xc0001107d0, 0xc000105890, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/stellar/go/vendor/github.com/sirupsen/logrus/entry.go:112 +0x23f
github.com/stellar/go/vendor/github.com/sirupsen/logrus.(*Entry).Panic(0xc000110870, 0xc0005259f0, 0x1, 0x1)
	/go/src/github.com/stellar/go/vendor/github.com/sirupsen/logrus/entry.go:180 +0xb2
github.com/stellar/go/support/log.(*Entry).Panic(0xc000110870, 0xc0005259f0, 0x1, 0x1)
	/go/src/github.com/stellar/go/support/log/entry.go:130 +0x4b
github.com/stellar/go/support/log.Panic(0xc0005259f0, 0x1, 0x1)
	/go/src/github.com/stellar/go/support/log/main.go:155 +0x4b
github.com/stellar/go/services/horizon/internal.initExpIngester(0xc00014a780, 0xc0000e2040)
	/go/src/github.com/stellar/go/services/horizon/internal/init.go:85 +0x22b
github.com/stellar/go/services/horizon/internal.(*App).init(0xc00014a780)
	/go/src/github.com/stellar/go/services/horizon/internal/app.go:407 +0x785
github.com/stellar/go/services/horizon/internal.NewApp(0xc00004400d, 0x46, 0xc00003e01a, 0x52, 0x7fffc19d5460, 0x2a, 0xc000391190, 0x1, 0x1, 0x1f40, ...)
	/go/src/github.com/stellar/go/services/horizon/internal/app.go:75 +0xe2
github.com/stellar/go/services/horizon/cmd.initApp(0x0)
	/go/src/github.com/stellar/go/services/horizon/cmd/root.go:333 +0x62
github.com/stellar/go/services/horizon/cmd.glob..func11(0x1556780, 0xc0002d6b60, 0x0, 0xd)
	/go/src/github.com/stellar/go/services/horizon/cmd/root.go:28 +0x22
github.com/stellar/go/vendor/github.com/spf13/cobra.(*Command).execute(0x1556780, 0xc0000300f0, 0xd, 0xd, 0x1556780, 0xc0000300f0)
	/go/src/github.com/stellar/go/vendor/github.com/spf13/cobra/command.go:603 +0x241
github.com/stellar/go/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1556780, 0x2, 0x4, 0x0)
	/go/src/github.com/stellar/go/vendor/github.com/spf13/cobra/command.go:689 +0x2cc
github.com/stellar/go/vendor/github.com/spf13/cobra.(*Command).Execute(0x1556780, 0x407460, 0xc0000440b8)
	/go/src/github.com/stellar/go/vendor/github.com/spf13/cobra/command.go:648 +0x2b
github.com/stellar/go/services/horizon/cmd.Execute()
	/go/src/github.com/stellar/go/services/horizon/cmd/root.go:374 +0x2d
main.main()
	/go/src/github.com/stellar/go/services/horizon/main.go:6 +0x20
```

Currently running migrations DOWN 2 so I can bring 0.18.0 back online. It seems to take significantly longer than the UP migrations.

@bartekn @tomquisel @tamirms

**Comment by bartekn** [comment]
Marcinx, not sure why the error message is obfuscated but it looks like you
don't have history archive urls set. Check 0.19.0 release notes for an
example.

Trying to run horizon-0.20.0 (using

**Comment by marcinx** [comment]
Okay, that's possible as we skipped 0.19.0. Thanks for the hint. I will check it out.

**Comment by marcinx** [comment]
Cool! Got Horizon 0.20.0 to run with that. Thanks for the help @bartekn.
