### ISSUE TITLE
build_release_artifacts fails to build bifrost 

### ISSUE THREAD

**Issue by tomerweller** [stellar/go#202]
After re-basing today.

```sh
⇒  go run ./support/scripts/build_release_artifacts/main.go
INFO[0000] running: rm -rf dist/*                        pid=4385
INFO[0000] running: git describe --always --dirty        pid=4385
INFO[0000] running: mkdir -p dist/bifrost-snapshot-darwin-amd64  pid=4385
INFO[0000] running: cp LICENSE-APACHE.txt dist/bifrost-snapshot-darwin-amd64  pid=4385
INFO[0000] running: cp COPYING dist/bifrost-snapshot-darwin-amd64  pid=4385
INFO[0000] running: cp services/bifrost/README.md dist/bifrost-snapshot-darwin-amd64  pid=4385
INFO[0000] running: cp services/bifrost/CHANGELOG.md dist/bifrost-snapshot-darwin-amd64  pid=4385
INFO[0000] building github.com/stellar/go/services/bifrost  pid=4385
INFO[0000] running: go build -o dist/bifrost-snapshot-darwin-amd64/bifrost -ldflags -X github.com/stellar/go/support/app.buildTime=2017-12-08T17:56:47-08:00 -X github.com/stellar/go/support/app.version=snapshot-c3f0341-dirty github.com/stellar/go/services/bifrost  pid=4385
go build github.com/stellar/go/vendor/github.com/ethereum/go-ethereum/crypto/secp256k1: build constraints exclude all Go files in /home/weller/go/src/github.com/stellar/go/vendor/github.com/ethereum/go-ethereum/crypto/secp256k1
panic: exit status 1

goroutine 1 [running]:
main.build(0xc42014e630, 0x26, 0xc42014e660, 0x2a, 0xc420138020, 0x16, 0x798049, 0x6, 0x797cae, 0x5)
        /home/weller/go/src/github.com/stellar/go/support/scripts/build_release_artifacts/main.go:113 +0x9df
main.buildSnapshots()
        /home/weller/go/src/github.com/stellar/go/support/scripts/build_release_artifacts/main.go:186 +0x52d
main.main()
        /home/weller/go/src/github.com/stellar/go/support/scripts/build_release_artifacts/main.go:52 +0xc2
exit status 2
```

**Comment by bartekn** [comment]
You probably have CGO disabled. It also makes cross compilation harder.

I spent some time trying to figure out if we can get rid of `github.com/ethereum/go-ethereum/crypto/secp256k1` package but it seems that it's deeply integrated in `go-ethereum` package. I don't think we should develop our own geth client or use another one which isn't part of go-ethereum developers.

Proposed quick fix would be to skip cross-compilation for Bifrost (so travis will build linux version which seems fine now because very likely Bifrost will be deployed to linux servers).

To permanently fix cross-compilation we can use Docker.

**Comment by bartekn** [comment]
I believe this is fixed.
