### ISSUE TITLE
services/ticker crash on "ingest assets"

### ISSUE THREAD

**Issue by jacekn** [stellar/go#2326]
### What did you do?

I was trying to ingest asset data into fresh DB like this:
```
ticker ingest assets --db-url=XXX
```

### What did you expect to see?

Successful run

### What did you see instead?

It run for around 10s and then failed:
```
time="2020-02-26T12:20:36.931Z" level=debug msg="Total assets processed: 9048" pid=1
time="2020-02-26T12:20:36.931Z" level=debug msg="Total assets processed: 9049" pid=1
time="2020-02-26T12:20:36.931Z" level=debug msg="Total assets processed: 9050" pid=1
time="2020-02-26T12:20:36.931Z" level=debug msg="Total assets processed: 9051" pid=1
time="2020-02-26T12:20:36.931Z" level=debug msg="Total assets processed: 9052" pid=1
time="2020-02-26T12:20:36.931Z" level=debug msg="Total assets processed: 9053" pid=1
time="2020-02-26T12:20:36.931Z" level=debug msg="Total assets processed: 9054" pid=1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x8b8c22]

goroutine 401 [running]:
github.com/stellar/go/services/ticker/internal/scraper.fetchTOMLData(0xc000650140, 0x35, 0x0, 0xc00056b530, 0x10, 0xc00056b529, 0x3, 0xc000650180, 0x38, 0xc000578ff0, ...)
        /src/ticker/services/ticker/internal/scraper/asset_scraper.go:78 +0x122
github.com/stellar/go/services/ticker/internal/scraper.processAsset(0xc000650140, 0x35, 0x0, 0xc00056b530, 0x10, 0xc00056b529, 0x3, 0xc000650180, 0x38, 0xc000578ff0, ...)
        /src/ticker/services/ticker/internal/scraper/asset_scraper.go:218 +0x1c2
github.com/stellar/go/services/ticker/internal/scraper.(*ScraperConfig).parallelProcessAssets.func1(0x13, 0x2450, 0xc00092c000, 0x2450, 0x2a49, 0xf02a01, 0xc00050e0c0, 0xc00050e0b8, 0xc0001be6c0, 0x153a)
        /src/ticker/services/ticker/internal/scraper/asset_scraper.go:256 +0x264
created by github.com/stellar/go/services/ticker/internal/scraper.(*ScraperConfig).parallelProcessAssets
        /src/ticker/services/ticker/internal/scraper/asset_scraper.go:247 +0x1e4
```

Extra info:
If I add "--testnet" flag it works fine

**Comment by accordeiro** [comment]
Thanks for reporting @jacekn (and thanks for assigning it @ire-and-curses)! We'll investigate this :)
