### ISSUE TITLE
txnbuild: calling Transaction.Build() on a default Transaction panics

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/go#2411]
### What version are you using?

stellar/go@bab6abc8fbf3de9a932faa4c0da71b76d22f0932

### What did you do?

```go
tx := txnbuild.Transaction{}
err := tx.Build()
if err != nil {
	fmt.Println(err)
	return
}
fmt.Println(tx)
```

### What did you expect to see?

An error returned by the call to `Build()` indicating a required field isn't set.

### What did you see instead?

Panic.

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x684017]

goroutine 19 [running]:
testing.tRunner.func1.1(0x72c540, 0xa2ec20)
        /home/leighmcculloch/local/bin/go/1.14/src/testing/testing.go:941 +0x3d0
testing.tRunner.func1(0xc0000dc5a0)
        /home/leighmcculloch/local/bin/go/1.14/src/testing/testing.go:944 +0x3f9
panic(0x72c540, 0xa2ec20)
        /home/leighmcculloch/local/bin/go/1.14/src/runtime/panic.go:967 +0x15d
github.com/stellar/go/txnbuild.(*Transaction).Build(0xc00002e5b0, 0x9f21f2, 0x9f21f2)
        /home/leighmcculloch/devel/stellar--go/txnbuild/transaction.go:111 +0x177
```

**Comment by bartekn** [comment]
Presumably fixed by https://github.com/stellar/go/pull/2495.
