### ISSUE TITLE
fatal error: runtime: out of memory while processing ledger entry changes

### ISSUE THREAD

**Issue by abuiles** [stellar/go#2449]
Another issue during verify-range FROM: 24116927 TO: 24123327

```

18:39:04
time="2020-04-03T18:39:04.061Z" level=info msg="Processing ledger entry changes" numEntries=5000000 pid=1097 sequence=24116927 service=expingest source=historyArchive

18:39:15
fatal error: runtime: out of memory

18:39:15
runtime stack:

18:39:15
runtime.throw(0xf63560, 0x16)

18:39:15
/usr/local/go/src/runtime/panic.go:774 +0x72

18:39:15
runtime.sysMap(0xc178000000, 0x54000000, 0x1923af8)

18:39:15
/usr/local/go/src/runtime/mem_linux.go:169 +0xc5

18:39:15
runtime.(*mheap).sysAlloc(0x190b3e0, 0x50c00000, 0x0, 0x0)

18:39:15
/usr/local/go/src/runtime/malloc.go:701 +0x1cd

18:39:15
runtime.(*mheap).grow(0x190b3e0, 0x28600, 0xffffffff)

18:39:15
/usr/local/go/src/runtime/mheap.go:1255 +0xa3

18:39:15
runtime.(*mheap).allocSpanLocked(0x190b3e0, 0x28600, 0x1923b08, 0x41fb45)

18:39:15
/usr/local/go/src/runtime/mheap.go:1170 +0x266

18:39:15
runtime.(*mheap).alloc_m(0x190b3e0, 0x28600, 0x7fc3e5ed0100, 0x7fc3e5ed8d00)

18:39:15
/usr/local/go/src/runtime/mheap.go:1022 +0xc2

18:39:15
runtime.(*mheap).alloc.func1()

18:39:15
/usr/local/go/src/runtime/mheap.go:1093 +0x4c

18:39:15
runtime.(*mheap).alloc(0x190b3e0, 0x28600, 0x7fc40a010100, 0x7fc3e5ed8d00)

18:39:15
/usr/local/go/src/runtime/mheap.go:1092 +0x8a

18:39:15
runtime.largeAlloc(0x50c00000, 0x450001, 0x7fc3e5ed8d00)

18:39:15
/usr/local/go/src/runtime/malloc.go:1138 +0x97

18:39:15
runtime.mallocgc.func1()

18:39:15
/usr/local/go/src/runtime/malloc.go:1033 +0x46

18:39:15
runtime.systemstack(0x0)

18:39:15
/usr/local/go/src/runtime/asm_amd64.s:370 +0x66

18:39:15
runtime.mstart()

18:39:15
/usr/local/go/src/runtime/proc.go:1146

18:39:15
goroutine 25 [running]:

18:39:15
runtime.systemstack_switch()

18:39:15
/usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc001bf73e8 sp=0xc001bf73e0 pc=0x45e8b0
	/usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc001bf73e8 sp=0xc001bf73e0 pc=0x45e8b0

18:39:15
runtime.mallocgc(0x50c00000, 0xea4ce0, 0x7fc3f0c58f01, 0xc001bf7540)

18:39:15
/usr/local/go/src/runtime/malloc.go:1032 +0x895 fp=0xc001bf7488 sp=0xc001bf73e8 pc=0x40e465

18:39:15
runtime.newarray(0xea4ce0, 0x880000, 0x203007)

18:39:15
/usr/local/go/src/runtime/malloc.go:1173 +0x63 fp=0xc001bf74b8 sp=0xc001bf7488 pc=0x40e8a3

18:39:15
runtime.makeBucketArray(0xdfef60, 0xc001bf7d17, 0x0, 0x40dee6, 0xc01dbc0680)

18:39:15
/usr/local/go/src/runtime/map.go:362 +0x183 fp=0xc001bf74f0 sp=0xc001bf74b8 pc=0x40f793

18:39:15
runtime.hashGrow(0xdfef60, 0xc000114090)

18:39:15
/usr/local/go/src/runtime/map.go:1033 +0x89 fp=0xc001bf7540 sp=0xc001bf74f0 pc=0x411289

18:39:15
runtime.mapassign_faststr(0xdfef60, 0xc000114090, 0xc082e8c000, 0x64, 0xc01dbc0601)

18:39:15
/usr/local/go/src/runtime/map_faststr.go:272 +0x122 fp=0xc001bf75a8 sp=0xc001bf7540 pc=0x414ce2

18:39:15
github.com/stellar/go/exp/ingest/io.(*memoryTempSet).Add(0xc00031e0b0, 0xc082e8c000, 0x64, 0x0, 0x0)

18:39:15
/stellar-go/exp/ingest/io/memory_temp_set.go:19 +0x4e fp=0xc001bf75e0 sp=0xc001bf75a8 pc=0xb7aa7e

18:39:15
github.com/stellar/go/exp/ingest/io.(*SingleLedgerStateReader).streamBucketContents(0xc000324300, 0x643981b12a63cc14, 0x475010031576fc18, 0xe9a4d055043db6e3, 0xdce9a89e12780548, 0xdce9a89e12780500)

18:39:15
/stellar-go/exp/ingest/io/single_ledger_state_reader.go:431 +0x836 fp=0xc001bf7d88 sp=0xc001bf75e0 pc=0xb7c886

18:39:15
github.com/stellar/go/exp/ingest/io.(*SingleLedgerStateReader).streamBuckets(0xc000324300)

18:39:15
/stellar-go/exp/ingest/io/single_ledger_state_reader.go:195 +0x33d fp=0xc001bf7fd8 sp=0xc001bf7d88 pc=0xb7b84d

18:39:15
runtime.goexit()

18:39:15
/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc001bf7fe0 sp=0xc001bf7fd8 pc=0x460981

18:39:15
created by github.com/stellar/go/exp/ingest/io.(*SingleLedgerStateReader).Read.func1

18:39:15
/stellar-go/exp/ingest/io/single_ledger_state_reader.go:466 +0x3e

18:39:15
goroutine 1 [running]:

18:39:15
goroutine running on other thread; stack unavailable

18:39:15
goroutine 7 [chan receive]:

18:39:15
github.com/rcrowley/go-metrics.(*meterArbiter).tick(0x1904820)

18:39:15
/root/go/pkg/mod/github.com/rcrowley/go-metrics@v0.0.0-20181016184325-3113b8401b8a/meter.go:239 +0x31

18:39:15
created by github.com/rcrowley/go-metrics.NewMeter

18:39:15
/root/go/pkg/mod/github.com/rcrowley/go-metrics@v0.0.0-20181016184325-3113b8401b8a/meter.go:46 +0x111

18:39:15
goroutine 18 [chan receive, 8 minutes]:

18:39:15
github.com/getsentry/raven-go.(*Client).worker(0xc00034c000)

18:39:15
/root/go/pkg/mod/github.com/getsentry/raven-go@v0.0.0-20160805001729-c9d3cc542ad1/client.go:430 +0xec

18:39:15
created by github.com/getsentry/raven-go.newClient

18:39:15
/root/go/pkg/mod/github.com/getsentry/raven-go@v0.0.0-20160805001729-c9d3cc542ad1/client.go:308 +0xf8

18:39:15
goroutine 19 [syscall, 8 minutes]:

18:39:15
os/signal.signal_recv(0x0)

18:39:15
/usr/local/go/src/runtime/sigqueue.go:147 +0x9c

18:39:15
os/signal.loop()

18:39:15
/usr/local/go/src/os/signal/signal_unix.go:23 +0x22

18:39:15
created by os/signal.init.0

18:39:15
/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

18:39:15
goroutine 52 [select, 8 minutes]:

18:39:15
database/sql.(*DB).connectionResetter(0xc00001a000, 0x11c05c0, 0xc0002d6000)

18:39:15
/usr/local/go/src/database/sql/sql.go:1065 +0xfb

18:39:15
created by database/sql.OpenDB

18:39:15
/usr/local/go/src/database/sql/sql.go:723 +0x193

18:39:15
goroutine 51 [select, 8 minutes]:

18:39:15
database/sql.(*DB).connectionOpener(0xc00001a000, 0x11c05c0, 0xc0002d6000)

18:39:15
/usr/local/go/src/database/sql/sql.go:1052 +0xe8

18:39:15
created by database/sql.OpenDB

18:39:15
/usr/local/go/src/database/sql/sql.go:722 +0x15d

18:39:15
goroutine 37 [select, 8 minutes]:

18:39:15
database/sql.(*DB).connectionOpener(0xc00034c180, 0x11c05c0, 0xc00007c100)

18:39:15
/usr/local/go/src/database/sql/sql.go:1052 +0xe8

18:39:15
created by database/sql.OpenDB

18:39:15
/usr/local/go/src/database/sql/sql.go:722 +0x15d

18:39:15
goroutine 38 [select, 8 minutes]:

18:39:15
database/sql.(*DB).connectionResetter(0xc00034c180, 0x11c05c0, 0xc00007c100)

18:39:15
/usr/local/go/src/database/sql/sql.go:1065 +0xfb

18:39:15
created by database/sql.OpenDB

18:39:15
/usr/local/go/src/database/sql/sql.go:723 +0x193

18:39:15
goroutine 54 [select, 8 minutes]:

18:39:15
github.com/lib/pq.(*conn).watchCancel.func1(0xc00003a5a0, 0xc0000cc000, 0xc000386300)

18:39:15
/root/go/pkg/mod/github.com/lib/pq@v1.2.0/conn_go18.go:94 +0xb2

18:39:15
created by github.com/lib/pq.(*conn).watchCancel

18:39:15
/root/go/pkg/mod/github.com/lib/pq@v1.2.0/conn_go18.go:93 +0x9c

18:39:15
goroutine 55 [chan receive, 8 minutes]:

18:39:15
database/sql.(*Tx).awaitDone(0xc000324500)

18:39:15
/usr/local/go/src/database/sql/sql.go:2002 +0x4b

18:39:15
created by database/sql.(*DB).beginDC

18:39:15
/usr/local/go/src/database/sql/sql.go:1723 +0x1b4

18:39:15
goroutine 129 [select, 3 minutes]:

18:39:15
net/http.(*persistConn).readLoop(0xc00033ed80)

18:39:15
/usr/local/go/src/net/http/transport.go:2027 +0x999

18:39:15
created by net/http.(*Transport).dialConn

18:39:15
/usr/local/go/src/net/http/transport.go:1575 +0xb0d

18:39:15
goroutine 226 [select, 3 minutes]:

18:39:15
net/http.(*persistConn).writeLoop(0xc00033ed80)

18:39:15
/usr/local/go/src/net/http/transport.go:2205 +0x123

18:39:15
created by net/http.(*Transport).dialConn

18:39:15
/usr/local/go/src/net/http/transport.go:1576 +0xb32
```

**Comment by abuiles** [comment]
Found another instance of this while running verify range FROM: 24112383 TO: 24120063

```

10:14:53
time="2020-04-07T10:14:53.140Z" level=info msg="Processing ledger entry changes" numEntries=5100000 pid=1223 sequence=24112383 service=expingest source=historyArchive

10:14:53
fatal error: runtime: out of memory

10:14:53
runtime stack:

10:14:53
runtime.throw(0xf631ea, 0x16)

10:14:53
/usr/local/go/src/runtime/panic.go:774 +0x72

10:14:53
runtime.sysMap(0xc17c000000, 0x54000000, 0x1923af8)

10:14:53
/usr/local/go/src/runtime/mem_linux.go:169 +0xc5

10:14:53
runtime.(*mheap).sysAlloc(0x190b3e0, 0x50c00000, 0x40e040, 0xffffffff00060dbd)
```

**Comment by abuiles** [comment]
One more 
FROM: 24104703 TO: 24112383

```
10:27:25
time="2020-04-07T10:27:25.418Z" level=info msg="Batch added to StateVerifier" ledger=24112383 pid=1223 service=expingest subservice=state_verify total=5100000

10:27:28
fatal error: runtime: out of memory

10:27:28
runtime stack:

10:27:28
runtime.throw(0xf631ea, 0x16)

10:27:28
/usr/local/go/src/runtime/panic.go:774 +0x72

10:27:28
runtime.sysMap(0xc198000000, 0x54000000, 0x1923af8)
```

**Comment by tamirms** [comment]
I ran `docker run -d -e BRANCH=release-horizon-v1.1.0 -e FROM=24112383 -e TO=24114303 stellar/exp-verify-range` locally and it seems that the history archive snapshot at ledger 24112383 is particularly large. While processing that snapshot the docker container memory usage reached 7.1GB and throughout the entire job the peak memory usage was around 8.2GB.

Perhaps the reason why we didn't see this error in older releases is that when the entire ledger history range was divided into chunks, none of the chunks included  `24112383` or other snapshots which were really large.

To fix this when running AWS batch, I think we should set the memory limit for the job to 9GB

**Comment by ire-and-curses** [comment]
Wow that's kind of amazing. Agree about the limit increase. Maybe this increases the value of implementing in-memory streaming (https://github.com/stellar/go/issues/2128)? What do you think?

**Comment by tamirms** [comment]
@ire-and-curses https://github.com/stellar/go/issues/2128 would not help in this situation because the history archive snapshot is what's taking up a lot of memory, not the streaming of individual ledgers in between history archive snapshots.

The way verify range job works is that there is a start ledger and end ledger. The start and end ledgers are checkpoint ledgers. The job starts by loading all entries from the history archive snapshot corresponding to the start ledger. Then it proceeds to stream all subsequent ledgers from stellar core until it reaches the end ledger. At this point, we load the history archive snapshot corresponding to the end ledger and check that all the rows in the database match the entries in the history archive snapshot.

**Comment by abuiles** [comment]
@tamirms 👍  - I'll check if we can get more memory the next time. Also, creating smaller batches helped with some of this.
