### ISSUE TITLE
Valid transaction containing empty manage data cannot be decoded by horizonclient-v3.0.0

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/go#2572]
### What version are you using?

`horizonclient-v3.0.0`

### What did you do?

@qiwu7 opened a PR #2571 showing that transaction [8efecaf...c84c418](https://horizon-testnet.stellar.org/transactions/8efecaf966f11bb8b8d95defde22c551594cba4f9931c520719781235c84c418) when decoded with the latest release of horizonclient/txnbuild will raise an error.

https://github.com/stellar/go/blob/d9f35035cc4cd92bd6d4db494f109c6ea388cda8/main.go#L9-L10

### What did you expect to see?

Successfully parsed transaction like what happens when parsing this transaction with txnbuild from horizonclient-v2.2.0.

### What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1252fba]

goroutine 1 [running]:
github.com/stellar/go/txnbuild.(*ManageData).FromXDR(0xc0000d22c0, 0xc0000a51e0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/qiwu/go/src/github.com/stellar/go/txnbuild/manage_data.go:47 +0xea
github.com/stellar/go/txnbuild.operationFromXDR(0xc0000a51e0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/qiwu/go/src/github.com/stellar/go/txnbuild/operation.go:59 +0xad
github.com/stellar/go/txnbuild.transactionFromParsedXDR(0x2, 0x0, 0xc0000ca1b0, 0x0, 0x0, 0x0, 0xc0000991e0)
	/Users/qiwu/go/src/github.com/stellar/go/txnbuild/transaction.go:484 +0xae2
github.com/stellar/go/txnbuild.TransactionFromXDR(0x12faabe, 0x3cc, 0xc000101f10, 0x2, 0x2)
	/Users/qiwu/go/src/github.com/stellar/go/txnbuild/transaction.go:419 +0xe7
main.main()
	/Users/qiwu/go/src/github.com/stellar/go/main.go:14 +0x17a
exit status 2
```

**Comment by leighmcculloch** [comment]
The transaction @qiwu7 shared which is linked above has a few operations in it but it is easy to reproduce this bug with a transaction that has a single manage data operation and a nil value. The lib will allow the creation of the transaction but decoding the transaction will panic.

If the nil value is changed to be an empty byte array (`[]byte(nil)` => `[]byte{}`) the transaction will parse successfully.

Here is an example of that:

```go
package main

import (
	"fmt"

	"github.com/stellar/go/txnbuild"
)

func main() {
	op := txnbuild.ManageData{
		Name:  "key",
		Value: []byte(nil), // <<<<<<<<<<<<<<<<<<<<
	}

	tx, err := txnbuild.NewTransaction(
		txnbuild.TransactionParams{
			SourceAccount: &txnbuild.SimpleAccount{AccountID: "GDYHQK7C2OMUMU3I6553YDQ56RUQL2JFL6FPYOYGLDKS3QGXDC4SRLOW"},
			Operations:    []txnbuild.Operation{&op},
			BaseFee:       txnbuild.MinBaseFee,
			Timebounds:    txnbuild.NewInfiniteTimeout(),
		},
	)
	if err != nil {
		panic(err)
	}

	txe, err := tx.Base64()
	if err != nil {
		panic(err)
	}

	fmt.Println(txe)

	parsed, err := txnbuild.TransactionFromXDR(txe)
	if err != nil {
		panic(err)
	}

	fmt.Println(parsed)
}
```

Transaction with nil byte array as value:
```
AAAAAPB4K+LTmUZTaPd7vA4d9GkF6SVfivw7BljVLcDXGLkoAAAAZAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAKAAAAA2tleQAAAAAAAAAAAAAAAAA=                                                               
```

Transaction with empty byte array as value:
```
AAAAAPB4K+LTmUZTaPd7vA4d9GkF6SVfivw7BljVLcDXGLkoAAAAZAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAKAAAAA2tleQAAAAABAAAAAAAAAAAAAAAA                                                           
```

**Comment by leighmcculloch** [comment]
I don't see any changes to manage data op code for a long time so it is possible my reduced example above is a red herring.

**Comment by leighmcculloch** [comment]
The fix for this issue is released is in [v3.0.1](https://github.com/stellar/go/releases/tag/horizonclient-v3.0.1).
