### ISSUE TITLE
Horizon admin port panic

### ISSUE THREAD

**Issue by jacekn** [stellar/go#2714]
### What version are you using?

horizon 1.4.0-77

### What did you do?

With ADMIN_PORT enabled I made a http GET request:
```
curl http://127.0.0.1:6060/metrics
```
### What did you expect to see?

Metrics

### What did you see instead?

```
curl: (52) Empty reply from server
```

And the following in journalctl:
```
stellar-horizon[389]: 2020/06/18 14:43:50 http: panic serving 127.0.0.1:37930: runtime error: invalid memory address or nil pointer dereference
stellar-horizon[389]: goroutine 492357209 [running]:
stellar-horizon[389]: net/http.(*conn).serve.func1(0xc002aff900)
stellar-horizon[389]:         /usr/lib/go-1.13.3/src/net/http/server.go:1767 +0x139
stellar-horizon[389]: panic(0xe0efc0, 0x18d42b0)
stellar-horizon[389]:         /usr/lib/go-1.13.3/src/runtime/panic.go:679 +0x1b2
stellar-horizon[389]: github.com/stellar/go/services/horizon/internal/actions.(*MetricsHandler).PrometheusFormat(0xc0002dbcf0, 0x7f35229d90a8, 0xc00b5e8dc0, 0x7f35229d90a8, 0xc00b5e8dc0)
stellar-horizon[389]:         /var/lib/jenkins/jobs/stellar-horizon-public/workspace/services/horizon/internal/actions/metrics.go:19 +0x67
stellar-horizon[389]: github.com/stellar/go/services/horizon/internal.HandleMetrics.func1(0x7f35229d9078, 0xc00b5e8dc0, 0xc002b5fa00)
stellar-horizon[389]:         /var/lib/jenkins/jobs/stellar-horizon-public/workspace/services/horizon/internal/handler.go:646 +0x7f
stellar-horizon[389]: net/http.HandlerFunc.ServeHTTP(0xc00000e2a0, 0x7f35229d9078, 0xc00b5e8dc0, 0xc002b5fa00)
stellar-horizon[389]:         /usr/lib/go-1.13.3/src/net/http/server.go:2007 +0x44
stellar-horizon[389]: github.com/go-chi/chi.(*Mux).routeHTTP(0xc00024e960, 0x7f35229d9078, 0xc00b5e8dc0, 0xc002b5fa00)
stellar-horizon[389]:         /var/lib/jenkins/jobs/stellar-horizon-public/workspace/vendor/github.com/go-chi/chi/mux.go:425 +0x278
stellar-horizon[389]: net/http.HandlerFunc.ServeHTTP(0xc0002dbd00, 0x7f35229d9078, 0xc00b5e8dc0, 0xc002b5fa00)
stellar-horizon[389]:         /usr/lib/go-1.13.3/src/net/http/server.go:2007 +0x44
stellar-horizon[389]: github.com/stellar/go/services/horizon/internal.loggerMiddleware.func1(0x11a9ac0, 0xc005017dc0, 0xc002b5f900)
stellar-horizon[389]:         /var/lib/jenkins/jobs/stellar-horizon-public/workspace/services/horizon/internal/middleware.go:94 +0x335
stellar-horizon[389]: net/http.HandlerFunc.ServeHTTP(0xc00000e2c0, 0x11a9ac0, 0xc005017dc0, 0xc002b5f900)
stellar-horizon[389]:         /usr/lib/go-1.13.3/src/net/http/server.go:2007 +0x44
stellar-horizon[389]: github.com/go-chi/chi/middleware.RequestID.func1(0x11a9ac0, 0xc005017dc0, 0xc002b5f800)
stellar-horizon[389]:         /var/lib/jenkins/jobs/stellar-horizon-public/workspace/vendor/github.com/go-chi/chi/middleware/request_id.go:76 +0x1df
stellar-horizon[389]: net/http.HandlerFunc.ServeHTTP(0xc00000e320, 0x11a9ac0, 0xc005017dc0, 0xc002b5f800)
stellar-horizon[389]:         /usr/lib/go-1.13.3/src/net/http/server.go:2007 +0x44
stellar-horizon[389]: github.com/stellar/go/services/horizon/internal.appContextMiddleware.func1.1(0x11a9ac0, 0xc005017dc0, 0xc002b5f700)
stellar-horizon[389]:         /var/lib/jenkins/jobs/stellar-horizon-public/workspace/services/horizon/internal/middleware.go:35 +0x16a
stellar-horizon[389]: net/http.HandlerFunc.ServeHTTP(0xc00000e340, 0x11a9ac0, 0xc005017dc0, 0xc002b5f700)
stellar-horizon[389]:         /usr/lib/go-1.13.3/src/net/http/server.go:2007 +0x44
stellar-horizon[389]: github.com/go-chi/chi/middleware.StripSlashes.func1(0x11a9ac0, 0xc005017dc0, 0xc002b5f700)
stellar-horizon[389]:         /var/lib/jenkins/jobs/stellar-horizon-public/workspace/vendor/github.com/go-chi/chi/middleware/strip.go:25 +0xeb
stellar-horizon[389]: net/http.HandlerFunc.ServeHTTP(0xc00000e360, 0x11a9ac0, 0xc005017dc0, 0xc002b5f700)
stellar-horizon[389]:         /usr/lib/go-1.13.3/src/net/http/server.go:2007 +0x44
stellar-horizon[389]: github.com/go-chi/chi.(*Mux).ServeHTTP(0xc00024e960, 0x11a9ac0, 0xc005017dc0, 0xc0029b6f00)
stellar-horizon[389]:         /var/lib/jenkins/jobs/stellar-horizon-public/workspace/vendor/github.com/go-chi/chi/mux.go:82 +0x2b2
stellar-horizon[389]: net/http.serverHandler.ServeHTTP(0xc000250460, 0x11a9ac0, 0xc005017dc0, 0xc0029b6f00)
stellar-horizon[389]:         /usr/lib/go-1.13.3/src/net/http/server.go:2802 +0xa4
stellar-horizon[389]: net/http.(*conn).serve(0xc002aff900, 0x11ae940, 0xc0099c4140)
stellar-horizon[389]:         /usr/lib/go-1.13.3/src/net/http/server.go:1890 +0x875
stellar-horizon[389]: created by net/http.(*Server).Serve
stellar-horizon[389]:         /usr/lib/go-1.13.3/src/net/http/server.go:2927 +0x38e
```

**Comment by csokun** [comment]
I ran into this problem once I configured `horizon serve` with `--remote-captive-core-url`.
