### ISSUE TITLE
Horizon metrics panic when run horizon serve with --remote-captive-core-url

### ISSUE THREAD

**Issue by csokun** [stellar/go#4240]
Hi team,

I recently experienced the same issue as https://github.com/stellar/go/issues/2714 except my setup is a bit different.

Horizon version 2.8.1
Kubernete 1.21

**Steps to repro:**

Launch remote-captive-core instance (e.g localhost:8001) then launch horizon serve as follow:

```bash
#!/bin/bash
# horizon startup script
export INGEST=true
export NETWORK_PASSPHRASE=xxx
export DATABASE_URL=!!!!secret!!!!
export PER_HOUR_RATE_LIMIT=216000
export INGEST_FAILED_TRANSACTIONS=true
export REMOTE_CAPTIVE_CORE_URL=http://<hostname>:<captive-core-port>
export STELLAR_CORE_URL=http://<hostname>:11626
export HISTORY_ARCHIVE_URLS=...
export ENABLE_CAPTIVE_CORE_INGESTION=true
export ADMIN_PORT=9473

horizon serve
```

When horizon server is up & running `curl localhost:9473/metrics` horizon log the following details:

```bash
2022/02/23 03:48:35 http: panic serving 127.0.0.1:46664: runtime error: invalid memory address or nil pointer dereferencegoroutine 1109 [running]:net/http.(*conn).serve.func1(0xc0001f1ae0)        /usr/local/go/src/net/http/server.go:1824 +0x153
panic(0xfe4bc0, 0x19c1990)
        /usr/local/go/src/runtime/panic.go:971 +0x499
github.com/stellar/go/services/horizon/internal/ingest.(*system).initMetrics.func2(0xc000100400)
        /src/services/horizon/internal/ingest/main.go:336 +0x46
github.com/prometheus/client_golang/prometheus.(*valueFunc).Write(0xc0004d6b80, 0xc0003a7730, 0x1, 0x2)
        /go/pkg/mod/github.com/prometheus/client_golang@v0.9.3-0.20190127221311-3c4408c8b829/prometheus/value.go:72 +0x2bgithub.com/prometheus/client_golang/prometheus.processMetric(0x13464f8, 0xc0004d6b80, 0xc0007a13c8, 0xc0007a13f8, 0x0, 0x0, 0x1)        /go/pkg/mod/github.com/prometheus/client_golang@v0.9.3-0.20190127221311-3c4408c8b829/prometheus/registry.go:586 +0xa2github.com/prometheus/client_golang/prometheus.(*Registry).Gather(0xc0003afbd0, 0x0, 0x0, 0x0, 0x0, 0x0)        /go/pkg/mod/github.com/prometheus/client_golang@v0.9.3-0.20190127221311-3c4408c8b829/prometheus/registry.go:480 +0x9da
github.com/prometheus/client_golang/prometheus/promhttp.HandlerFor.func1(0x7f355b444630, 0xc000393dc0, 0xc00029b600)
        /go/pkg/mod/github.com/prometheus/client_golang@v0.9.3-0.20190127221311-3c4408c8b829/prometheus/promhttp/http.go:104 +0x87
net/http.HandlerFunc.ServeHTTP(0xc00094c2d0, 0x7f355b444630, 0xc000393dc0, 0xc00029b600)        /usr/local/go/src/net/http/server.go:2069 +0x44
net/http.HandlerFunc.ServeHTTP(0xc000942030, 0x7f355b444630, 0xc000393dc0, 0xc00029b600)
        /usr/local/go/src/net/http/server.go:2069 +0x44
github.com/go-chi/chi.(*Mux).routeHTTP(0xc000147b00, 0x7f355b444630, 0xc000393dc0, 0xc00029b600)
        /go/pkg/mod/github.com/go-chi/chi@v4.0.3+incompatible/mux.go:425 +0x28b
net/http.HandlerFunc.ServeHTTP(0xc000116010, 0x7f355b444630, 0xc000393dc0, 0xc00029b600)
        /usr/local/go/src/net/http/server.go:2069 +0x44
github.com/stellar/go/services/horizon/internal/httpx.loggerMiddleware.func1.1(0x134cdb0, 0xc000178460, 0xc00029b500)
        /src/services/horizon/internal/httpx/middleware.go:84 +0x327
net/http.HandlerFunc.ServeHTTP(0xc00093e000, 0x134cdb0, 0xc000178460, 0xc00029b500)
        /usr/local/go/src/net/http/server.go:2069 +0x44
github.com/go-chi/chi/middleware.RequestID.func1(0x134cdb0, 0xc000178460, 0xc00029b400)        /go/pkg/mod/github.com/go-chi/chi@v4.0.3+incompatible/middleware/request_id.go:76 +0x1ebnet/http.HandlerFunc.ServeHTTP(0xc000942048, 0x134cdb0, 0xc000178460, 0xc00029b400)        /usr/local/go/src/net/http/server.go:2069 +0x44github.com/go-chi/chi/middleware.StripSlashes.func1(0x134cdb0, 0xc000178460, 0xc00029b400)
        /go/pkg/mod/github.com/go-chi/chi@v4.0.3+incompatible/middleware/strip.go:25 +0xee
net/http.HandlerFunc.ServeHTTP(0xc000942060, 0x134cdb0, 0xc000178460, 0xc00029b400)
        /usr/local/go/src/net/http/server.go:2069 +0x44
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc000147b00, 0x134cdb0, 0xc000178460, 0xc00029b300)
        /go/pkg/mod/github.com/go-chi/chi@v4.0.3+incompatible/mux.go:82 +0x2d1
net/http.serverHandler.ServeHTTP(0xc0001781c0, 0x134cdb0, 0xc000178460, 0xc00029b300)        /usr/local/go/src/net/http/server.go:2887 +0xa3net/http.(*conn).serve(0xc0001f1ae0, 0x13521f8, 0xc000393c80)
        /usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3013 +0x39b
```

Please kindly advise on the matter or point me to resources related to remote-captive-core setup would be much appreciated :)

**Comment by mollykarcher** [comment]
Remote captive-core has been deprecated
