### ISSUE TITLE
panic: base32 decode failed: illegal base32 data at input byte 0

### ISSUE THREAD

**Issue by dpblnt** [stellar/go#4393]
### What version are you using?
tag horizon-v2.17.0-branch

### What did you do?
run horizon with captive-core

### What did you expect to see?
warn: base32 decode failed: illegal base32 data at input byte 0
INFO[2022-05-22T12:54:24.092+03:00] ...

### What did you see instead?
INFO[2022-05-22T12:54:24.042+03:00] Herder: Quorum information for 40984476 : {"agree":23,"cost":34148728,"delayed":0,"disagree":0,"fail_at":6,"hash":"b68a69","lag_ms":2752,"ledger":40984476,"missing":0,"phase":"EXTERNALIZE"}  pid=25484 service=ingest subservice=stellar-core
INFO[2022-05-22T12:54:24.053+03:00] Ledger: Got consensus: [seq=40984478, prev=39484d, txs=313, ops=1000, sv: [ SIGNED@SatoshiPay_DE_Frankfurt txH: 11e595, ct: 1653213260, upgrades: [ ] ]]  pid=25484 service=ingest subservice=stellar-core
INFO[2022-05-22T12:54:24.092+03:00] Tx: applying ledger 40984478 (txs:313, ops:1000, base_fee:5000)  pid=25484 service=ingest subservice=stellar-core
panic: base32 decode failed: illegal base32 data at input byte 0

goroutine 136 [running]:
github.com/stellar/go/xdr.MustAddress(...)
        /opt/monorepo/xdr/account_id.go:84
github.com/stellar/go/services/horizon/internal/ingest.offerToXDR({{0xc04eea2b40, 0x38}, 0x352474ed, {0x1, 0xc05b5c9aa0, 0x0}, {0x0, 0x0, 0x0}, 0x15d195b77d2, ...})
        /opt/monorepo/services/horizon/internal/ingest/verify.go:535 +0x153
github.com/stellar/go/services/horizon/internal/ingest.(*OrderBookStream).verifyAllOffers(0xc0000c4360, {0x12c3510, 0xc00007fb80}, {0xc0d9a04000, 0x2715f2d02715f2d, 0x1a5255})
        /opt/monorepo/services/horizon/internal/ingest/orderbook.go:234 +0x6f8
github.com/stellar/go/services/horizon/internal/ingest.(*OrderBookStream).Update(0xc0000c4360, {0x12c3510, 0xc00007fb80})
        /opt/monorepo/services/horizon/internal/ingest/orderbook.go:355 +0x2ff
github.com/stellar/go/services/horizon/internal/ingest.(*OrderBookStream).Run(0x0, {0x12c3510, 0xc00007fb80})
        /opt/monorepo/services/horizon/internal/ingest/orderbook.go:387 +0x133
created by github.com/stellar/go/services/horizon/internal.(*App).Serve
        /opt/monorepo/services/horizon/internal/app.go:93 +0x205

**Comment by 2opremio** [comment]
Can you share the exact sequence of command you ran?

**Comment by 2opremio** [comment]
Can you reproduce (e.g. through reingestion)? We didn't observe that error at SDF

**Comment by dpblnt** [comment]
I can not reproduce it.
It happened only once.

**Comment by bartekn** [comment]
@dpblnt did you build the binary yourself? Did you make any changes to the code? I'm looking at paths (`/opt/monorepo`) and this binary was not built by SDF.

**Comment by dpblnt** [comment]
Yes it was built by me.
No I have not modified anything in the code.

**Comment by bartekn** [comment]
Can you share the logs before the panic event?

**Comment by dpblnt** [comment]
I had no log-file set, this was captured from sdtout
