### ISSUE TITLE
stellar-archivist: stellar-archivist fails to complete the scan of archives with http backend 

### ISSUE THREAD

**Issue by satyamz** [stellar/go#4539]
### What version are you using?
```
stellar-archivist 0.1.1-6      amd64
```

### What did you do?
I started to sacn the Tier-1 archives and it failed due to panic in the code:

```log
$ stellar-archivist scan http://history.stellar.org/prd/core-live/core_live_001
time="2022-08-09T11:25:39Z" level=info msg="Scanning checkpoint files in range: [0x0000003f, 0x0282f53f]"
time="2022-08-09T11:25:46Z" level=info msg="Archive: 4096 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:25:53Z" level=info msg="Archive: 8192 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:26:01Z" level=info msg="Archive: 12288 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:26:08Z" level=info msg="Archive: 16384 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:26:16Z" level=info msg="Archive: 20480 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:26:23Z" level=info msg="Archive: 24576 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:26:33Z" level=info msg="Archive: 28672 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:26:44Z" level=info msg="Archive: 32768 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:26:55Z" level=info msg="Archive: 36864 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:27:12Z" level=info msg="Archive: 40960 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:27:29Z" level=info msg="Archive: 45056 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:27:44Z" level=info msg="Archive: 49152 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:28:01Z" level=info msg="Archive: 53248 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:28:17Z" level=info msg="Archive: 57344 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:28:33Z" level=info msg="Archive: 61440 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:28:47Z" level=info msg="Archive: 65536 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:29:01Z" level=info msg="Archive: 69632 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:29:16Z" level=info msg="Archive: 73728 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:29:31Z" level=info msg="Archive: 77824 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:29:48Z" level=info msg="Archive: 81920 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:30:13Z" level=info msg="Archive: 86016 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:30:37Z" level=info msg="Archive: 90112 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:31:01Z" level=info msg="Archive: 94208 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:31:25Z" level=info msg="Archive: 98304 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:31:50Z" level=info msg="Archive: 102400 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:32:14Z" level=info msg="Archive: 106496 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:32:38Z" level=info msg="Archive: 110592 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:33:02Z" level=info msg="Archive: 114688 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:33:27Z" level=info msg="Archive: 118784 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:33:51Z" level=info msg="Archive: 122880 history, 0 ledger, 0 transactions, 0 results, 0 scp"
time="2022-08-09T11:34:13Z" level=warning msg="http: Bad" method=HEAD status="500 Internal Server Error" url="http://history.stellar.org/prd/core-live/core_live_001/history/00/7b/38/history-007b38bf.json"
panic: Unkown status code=500

goroutine 54 [running]:
github.com/stellar/go/historyarchive.(*Archive).ScanCheckpointsSlow.func3(0xc0000945a0, 0xc000324500, 0xc000094540, 0xc0001102a0, 0xc0000b4740, 0xc0000b4744)
	/go/src/github.com/stellar/go/historyarchive/scan.go:77 +0x1c6
created by github.com/stellar/go/historyarchive.(*Archive).ScanCheckpointsSlow
	/go/src/github.com/stellar/go/historyarchive/scan.go:69 +0x21d
```

### What did you expect to see?
I expected `stellar-archivist` to report the results of the scan.

### What did you see instead?

`stellar-archivist` failed due to http endpoint being slow. I scanned the same archives using `s3:` endpoint and it succeeded. There should be an option in `stellar-archivist` to retry and fail gracefully with proper message if there's something really wrong with archives. This provides false positive results and it breaks automated scan for the Tier-1 history archives.

**Comment by jacekn** [comment]
This is similar to https://github.com/stellar/go/issues/2352 and may be a duplicate
