### ISSUE TITLE
Revalidate existing integration tests against docker image [Futurenet]

### ISSUE THREAD

**Issue by jcx120** [stellar/go#4647]
Revalidate existing integration tests against docker image against Futurenet 
(reference: https://github.com/stellar/go/issues/4625)

**Comment by sreuland** [comment]
soroban quickstart PR runs minimal set of CI integration tests configured against hosted Futurenet, and those are passing:

https://github.com/stellar/quickstart/pull/373

**Comment by sreuland** [comment]
ran into a regression at some point, the CI tests on quickstart are failing due to horizon ingestion parsing error against, futurenet:

```
time="2022-10-07T22:32:45.491Z" level=info msg="Processing entries from History Archive Snapshot" pid=23460 sequence=149503 service=ingest
time="2022-10-07T22:32:46.491Z" level=info msg="Finished request" app_name=undefined app_version=undefined bytes=4178 client_name=undefined client_version=undefined duration=0.001830334 host="localhost:8001" ip=127.0.0.1 ip_port="127.0.0.1:47760" method=GET path=/ pid=23460 referer=undefined req=1384c5028f80/ulxwsmsjGY-000003 route=/ status=200 streaming=false x_forwarder_for=
panic: Unknown entry type: LedgerEntryTypeContractData

goroutine 233 [running]:
github.com/stellar/go/xdr.(*LedgerEntry).LedgerKey(0xc00073dd28)
	github.com/stellar/go/xdr/ledger_entry.go:44 +0x933
github.com/stellar/go/ingest.(*CheckpointChangeReader).streamBucketContents(0xc0002d00b0, {0x80, 0xa3, 0xb6, 0xd6, 0xbf, 0xa4, 0x22, 0xc8, 0x8a, ...}, ...)
	github.com/stellar/go/ingest/checkpoint_change_reader.go:364 +0xf86
github.com/stellar/go/ingest.(*CheckpointChangeReader).streamBuckets(0xc0002d00b0)
	github.com/stellar/go/ingest/checkpoint_change_reader.go:229 +0x607
created by github.com/stellar/go/ingest.(*CheckpointChangeReader).Read.func1
	github.com/stellar/go/ingest/checkpoint_change_reader.go:513 +0x5a
starting horizon...

```

**Comment by sreuland** [comment]
after updating quickstart to use latest tagged version of soroban horizon with [ingestion fix](https://github.com/stellar/go/pull/4653), CI integration tests are passing on https://github.com/stellar/quickstart/pull/373
