### ISSUE TITLE
runtime error on horizon's reingest

### ISSUE THREAD

**Issue by cybist** [stellar/go#774]
horizon: v0.13.3
"horizon db reingest" has the following error.
`
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x933382]
goroutine 42 [running]:
github.com/stellar/go/services/horizon/internal/ingest.(*Session).ingestTrades(0xc000523e30)
        /home/xxx/horizon/src/github.com/stellar/go/services/horizon/internal/ingest/session.go:568 +0x2c2
github.com/stellar/go/services/horizon/internal/ingest.(*Session).ingestOperation(0xc000523e30)
        /home/xxx/horizon/src/github.com/stellar/go/services/horizon/internal/ingest/session.go:430 +0x217
github.com/stellar/go/services/horizon/internal/ingest.(*Session).ingestTransaction(0xc000523e30)
        /home/xxx/horizon/src/github.com/stellar/go/services/horizon/internal/ingest/session.go:636 +0xee
github.com/stellar/go/services/horizon/internal/ingest.(*Session).ingestLedger(0xc000523e30)
        /home/xxx/horizon/src/github.com/stellar/go/services/horizon/internal/ingest/session.go:399 +0xf7
github.com/stellar/go/services/horizon/internal/ingest.(*Session).Run(0xc000523e30)
        /home/xxx/horizon/src/github.com/stellar/go/services/horizon/internal/ingest/session.go:51 +0x1b4
github.com/stellar/go/services/horizon/internal/ingest.(*System).ReingestRange(0xc0002467e0, 0x24c0100e3e20c, 0x1, 0x1, 0xc000165ad0)
        /home/xxx/horizon/src/github.com/stellar/go/services/horizon/internal/ingest/system.go:193 +0x1dc
github.com/stellar/go/services/horizon/internal/ingest.(*System).ReingestAll(0xc0002467e0, 0x0, 0x0, 0x0)
        /home/xxx/horizon/src/github.com/stellar/go/services/horizon/internal/ingest/system.go:120 +0x244
main.reingest(0xc0002467e0, 0x14000e8, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/xxx/horizon/src/github.com/stellar/go/services/horizon/db.go:234 +0x175
main.glob..func7.2(0xc0002467e0, 0x14000e8, 0x0, 0x0, 0xc000150f60, 0xc000155af0)
        /home/xxx/stellar_custom_builds/horizon/src/github.com/stellar/go/services/horizon/db.go:180 +0x4d
created by main.glob..func7
        /home/xxx/horizon/src/github.com/stellar/go/services/horizon/db.go:179 +0x113
`
How can I solve this?

**Comment by cybist** [comment]
Cannot "reinest" restart half way?

**Comment by cybist** [comment]
src/github.com/stellar/go/services/horizon/internal/ingest/session.go:568
`
func (is *Session) ingestTrades() {
...
    before, _, err := is.Cursor.BeforeAndAfter(key)
...
    offerPrice := before.Data.Offer.Price
`
"offerPrice" has got "nil".

The following source seems simillar.
src/github.com/stellar/go/services/horizon/internal/ingest/session.go:463
`
func (is *Session) ingestSignerEffects(effects *EffectIngestion, op xdr.SetOptionsOp) {
...
    be, ae, err := is.Cursor.BeforeAndAfter(source.LedgerKey())
...
    // HACK (scott) 2017-11-27:  Prevent crashes when BeforeAndAfter fails to
    // correctly work.
    if be == nil || ae == nil {
            // TODO (scott) 2018-03-02: log some info to help us track down the crash, doofus
            return
    }
`
Is the same thing happening?
If so, can I set "return" at ingestTrades like ingestSignerEffects?
